### PR TITLE
繳交week10作業

### PR DESCRIPTION
**Pull request by JhanJoe**
彭彭老師晚安，我是詹硯喬
想來補交week10 作業：[http://34.209.154.176:8000/](http://34.209.154.176:8000/)
再麻煩老師了，謝謝!

### CODE REVIEW

**Comment by cwpeng** [comment]
I cannot review for you.

**Comment by JhanJoe** [comment]
對不起我忘了加老師為reviewer了orz
剛剛補上了!

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Comment by JhanJoe** [comment]
謝謝老師!

**Pull request merged**
